version: "3"
services:
  web-api:
    image: spinkelben/remote-radio-webapi:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
    depends_on:
      - redis
    environment:
      - MODE=dev
    volumes:
      - /media/sf_remote-radio/radio_api:/app:ro
      - socketvolume:/var/sockets
  radio:
    image: spinkelben/remote-radio-app:latest
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /media/sf_remote-radio/radio_app:/app:ro
      - socketvolume:/var/sockets
    environment:
      - LOGLEVEL="DEBUG"
  web-frontend:
    image: spinkelben/remote-radio-frontend:latest
    ports:
      - "80:80"
    networks:
      - webnet
    environment:
      - MODE=dev
    volumes:
      - /media/sf_remote-radio/radio_frontend:/app:ro
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
volumes:
  socketvolume: {}
